$(document).ready(function(){
	$('#dropdown-content').hide();
	$('#dropdown-content1').hide();
$('#registration').focus(
		function(){
			$('#dropdown-content').show();
		})
$('#login').focus(
		function(){
			$('#dropdown-content1').show();
		})
$('#studentRegistration').click(
		function(){
			$('#dropdown-content').hide();
		})
$('#register').click(
		function(){
			$('#dropdown-content').hide();
		})
$('#studentlogin').click(
		function(){
			$('#dropdown-content').hide();
		})
$('#instituteloginr').click(
		function(){
			$('#dropdown-content').hide();
		})
$('#state').click(
		function(){
			$('#dropdown-content').hide();
		})
$('#minister').click(
		function(){
			$('#dropdown-content').hide();
		})
});
